import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import React from "react";
import Variable from "@/components/Variable";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <header className="bg-red-700 px-9 py-0.3 flex gap-3 text-sm">
         
          <Link href="/contact-us">Contact Us</Link>
          <Link href="/React">React</Link>
          <Link href="/ThinkingReactUI">ThinkingReactUI</Link>
       </header>
       
       {children}
  
        <footer className="footer footer-center  py-0.3 bg-base-300 text-base-content">
          <p>&copy; 2024 - All rights reserved.</p>
        </footer>
        `
        </body>
    </html>
  );
}