import "../globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import React from "react";
import Button from "@/components/Button";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <header className="bg-gray-700 px-5 py-5 flex gap-5">
         
          <Link href="/contact-us">Contact Us</Link>
          <Link href="/cs_department/students">students</Link>
         
        </header>
        <main>{children}</main>
        {children}
        <footer className="bg-gray-500 flex justify-center py-5">
          <p>&copy; Booked by Gulf course</p>
        </footer>
      </body>
    </html>
  );
}